In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt                  # Importing required libraries
%matplotlib inline
import os
import sklearn
import warnings
warnings.filterwarnings("ignore")

#### Importing Real and fake news dataset from kaggle

In [2]:
os.chdir("C:\\Users\\ABC\\Desktop\\Fake news Analysis")
fake_news=pd.read_csv("fake.csv")
real_news=pd.read_csv("real_news.csv")

In [3]:
print(fake_news.shape,real_news.shape)

(12999, 20) (15712, 11)


In [4]:
fake_news.head()

uuid  ord_in_thread  \
0  6a175f46bcd24d39b3e962ad0f29936721db70db              0   
1  2bdc29d12605ef9cf3f09f9875040a7113be5d5b              0   
2  c70e149fdd53de5e61c29281100b9de0ed268bc3              0   
3  7cf7c15731ac2a116dd7f629bd57ea468ed70284              0   
4  0206b54719c7e241ffe0ad4315b808290dbe6c0f              0   

                 author                      published  \
0     Barracuda Brigade  2016-10-26T21:41:00.000+03:00   
1  reasoning with facts  2016-10-29T08:47:11.259+03:00   
2     Barracuda Brigade  2016-10-31T01:41:49.479+02:00   
3                Fed Up  2016-11-01T05:22:00.000+02:00   
4                Fed Up  2016-11-01T21:56:00.000+02:00   

                                               title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                                text language  \
0  Print They should pay all the back all the mon...  english   
1  Why Did Attorney General Loretta Lynch Plead T...  english   
2  Red State : \nFox News Sunday reported this mo...  english   
3  Email Kayla Mueller was a prisoner and torture...  english   
4  Email HEALTHCARE REFORM TO MAKE AMERICA GREAT ...  english   

                         crawled             site_url country  domain_rank  \
0  2016-10-27T01:49:27.168+03:00  100percentfedup.com      US      25689.0   
1  2016-10-29T08:47:11.259+03:00  100percentfedup.com      US      25689.0   
2  2016-10-31T01:41:49.479+02:00  100percentfedup.com      US      25689.0   
3  2016-11-01T15:46:26.304+02:00  100percentfedup.com      US      25689.0   
4  2016-11-01T23:59:42.266+02:00  100percentfedup.com      US      25689.0   

                                        thread_title  spam_score  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...       0.000   
1  Re: Why Did Attorney General Loretta Lynch Ple...       0.000   
2  BREAKING: Weiner Cooperating With FBI On Hilla...       0.000   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...       0.068   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...       0.865   

                                        main_img_url  replies_count  \
0  http://bb4sp.com/wp-content/uploads/2016/10/Fu...              0   
1  http://bb4sp.com/wp-content/uploads/2016/10/Fu...              0   
2  http://bb4sp.com/wp-content/uploads/2016/10/Fu...              0   
3  http://100percentfedup.com/wp-content/uploads/...              0   
4  http://100percentfedup.com/wp-content/uploads/...              0   

   participants_count  likes  comments  shares  type  
0                   1      0         0       0  bias  
1                   1      0         0       0  bias  
2                   1      0         0       0  bias  
3                   0      0         0       0  bias  
4                   0      0         0       0  bias

In [5]:
real_news.head()

Unnamed: 0  Unnamed: 0.1     id  \
0           0             0  17283   
1           8             8  17291   
2           9             9  17292   
3        2547          2547  20127   
4        2551          2551  20131   

                                               title     publication  \
0  House Republicans Fret About Winning Their Hea...  New York Times   
1  First, a Mixtape. Then a Romance. - The New Yo...  New York Times   
2  Calling on Angels While Enduring the Trials of...  New York Times   
3  U.S. Plans to Step Up Military Campaign Agains...  New York Times   
4  272 Slaves Were Sold to Save Georgetown. What ...  New York Times   

                                author        date    year  month  url  \
0                           Carl Hulse  2016-12-31  2016.0   12.0  NaN   
1                     Katherine Rosman  2016-12-31  2016.0   12.0  NaN   
2                          Andy Newman  2016-12-31  2016.0   12.0  NaN   
3  Michael S. Schmidt and Eric Schmitt  2016-12-21  2016.0   12.0  NaN   
4                     Rachel L. Swarns  2016-12-15  2016.0   12.0  NaN   

                                             content  
0  WASHINGTON  —   Congressional Republicans have...  
1  Just how   is Hillary Kerr, the    founder of ...  
2  Angels are everywhere in the Muñiz family’s ap...  
3  ABU DHABI, United Arab Emirates  —   The Obama...  
4  WASHINGTON  —   The human cargo was loaded on ...

#### Taking title, content and publication columns from real news data and adding a column label with entries as real

In [6]:
real_news2 = real_news[['title', 'content', 'publication']]
real_news2['label'] = 'real'
real_news2.head()

title  \
0  House Republicans Fret About Winning Their Hea...   
1  First, a Mixtape. Then a Romance. - The New Yo...   
2  Calling on Angels While Enduring the Trials of...   
3  U.S. Plans to Step Up Military Campaign Agains...   
4  272 Slaves Were Sold to Save Georgetown. What ...   

                                             content     publication label  
0  WASHINGTON  —   Congressional Republicans have...  New York Times  real  
1  Just how   is Hillary Kerr, the    founder of ...  New York Times  real  
2  Angels are everywhere in the Muñiz family’s ap...  New York Times  real  
3  ABU DHABI, United Arab Emirates  —   The Obama...  New York Times  real  
4  WASHINGTON  —   The human cargo was loaded on ...  New York Times  real

#### taking title, text and site from fake news data and adding a column label with entries named as fake 

In [7]:
fake_news2 = fake_news[['title', 'text','site_url']]
fake_news2['label'] = 'fake'
fake_news2.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                                text             site_url  \
0  Print They should pay all the back all the mon...  100percentfedup.com   
1  Why Did Attorney General Loretta Lynch Plead T...  100percentfedup.com   
2  Red State : \nFox News Sunday reported this mo...  100percentfedup.com   
3  Email Kayla Mueller was a prisoner and torture...  100percentfedup.com   
4  Email HEALTHCARE REFORM TO MAKE AMERICA GREAT ...  100percentfedup.com   

  label  
0  fake  
1  fake  
2  fake  
3  fake  
4  fake

In [8]:
site_urls = fake_news2['site_url']


site_urls2 = [x.split('.',1)[0] for x in site_urls]

fake_news2['site_url'] = site_urls2
fake_news2.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                                text         site_url label  
0  Print They should pay all the back all the mon...  100percentfedup  fake  
1  Why Did Attorney General Loretta Lynch Plead T...  100percentfedup  fake  
2  Red State : \nFox News Sunday reported this mo...  100percentfedup  fake  
3  Email Kayla Mueller was a prisoner and torture...  100percentfedup  fake  
4  Email HEALTHCARE REFORM TO MAKE AMERICA GREAT ...  100percentfedup  fake

#### Combining both fake and real news data

In [9]:
newlabels = ['title', 'content', 'publication', 'label']
real_news2.columns = newlabels
fake_news2.columns = newlabels


frames = [fake_news2, real_news2]
news_dataset = pd.concat(frames)
news_dataset.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                             content      publication label  
0  Print They should pay all the back all the mon...  100percentfedup  fake  
1  Why Did Attorney General Loretta Lynch Plead T...  100percentfedup  fake  
2  Red State : \nFox News Sunday reported this mo...  100percentfedup  fake  
3  Email Kayla Mueller was a prisoner and torture...  100percentfedup  fake  
4  Email HEALTHCARE REFORM TO MAKE AMERICA GREAT ...  100percentfedup  fake

In [10]:
news_dataset.label.value_counts()            #Final dataset consist real and fake news

real    15712
fake    12999
Name: label, dtype: int64

#### Making label column as 1 and 0

In [11]:
news_dataset["response"] = np.where(news_dataset["label"] == "real", 0, 1)
news_dataset.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                             content      publication label  \
0  Print They should pay all the back all the mon...  100percentfedup  fake   
1  Why Did Attorney General Loretta Lynch Plead T...  100percentfedup  fake   
2  Red State : \nFox News Sunday reported this mo...  100percentfedup  fake   
3  Email Kayla Mueller was a prisoner and torture...  100percentfedup  fake   
4  Email HEALTHCARE REFORM TO MAKE AMERICA GREAT ...  100percentfedup  fake   

   response  
0         1  
1         1  
2         1  
3         1  
4         1

#### Data cleaning

In [12]:
news_dataset.isnull().sum()

title          680
content         46
publication      0
label            0
response         0
dtype: int64

In [13]:
news_dataset=news_dataset.dropna()

In [14]:
news_dataset.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                             content      publication label  \
0  Print They should pay all the back all the mon...  100percentfedup  fake   
1  Why Did Attorney General Loretta Lynch Plead T...  100percentfedup  fake   
2  Red State : \nFox News Sunday reported this mo...  100percentfedup  fake   
3  Email Kayla Mueller was a prisoner and torture...  100percentfedup  fake   
4  Email HEALTHCARE REFORM TO MAKE AMERICA GREAT ...  100percentfedup  fake   

   response  
0         1  
1         1  
2         1  
3         1  
4         1

In [15]:
news_dataset.shape

(27985, 5)

#### Changing into lower letters

In [16]:
news_dataset['content'] = [entry.lower() for entry in news_dataset['content']]
news_dataset.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                             content      publication label  \
0  print they should pay all the back all the mon...  100percentfedup  fake   
1  why did attorney general loretta lynch plead t...  100percentfedup  fake   
2  red state : \nfox news sunday reported this mo...  100percentfedup  fake   
3  email kayla mueller was a prisoner and torture...  100percentfedup  fake   
4  email healthcare reform to make america great ...  100percentfedup  fake   

   response  
0         1  
1         1  
2         1  
3         1  
4         1

#### Removing punctation and doing word tokeninzer of content column

In [17]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+')
news_dataset['content']= [tokenizer.tokenize(entry) for entry in news_dataset['content']]

In [18]:
news_dataset.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                             content      publication label  \
0  [print, they, should, pay, all, the, back, all...  100percentfedup  fake   
1  [why, did, attorney, general, loretta, lynch, ...  100percentfedup  fake   
2  [red, state, fox, news, sunday, reported, this...  100percentfedup  fake   
3  [email, kayla, mueller, was, a, prisoner, and,...  100percentfedup  fake   
4  [email, healthcare, reform, to, make, america,...  100percentfedup  fake   

   response  
0         1  
1         1  
2         1  
3         1  
4         1

In [19]:
news_dataset['content']=[" ".join(content) for content in news_dataset['content'].values]

In [20]:
news_dataset['content'].head()

0    print they should pay all the back all the mon...
1    why did attorney general loretta lynch plead t...
2    red state fox news sunday reported this mornin...
3    email kayla mueller was a prisoner and torture...
4    email healthcare reform to make america great ...
Name: content, dtype: object

#### Removing stopwords

In [21]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [22]:
news_dataset['content'] = [w for w in news_dataset['content'] if not w in stop]
news_dataset.head()

title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...   
1  Re: Why Did Attorney General Loretta Lynch Ple...   
2  BREAKING: Weiner Cooperating With FBI On Hilla...   
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...   
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...   

                                             content      publication label  \
0  print they should pay all the back all the mon...  100percentfedup  fake   
1  why did attorney general loretta lynch plead t...  100percentfedup  fake   
2  red state fox news sunday reported this mornin...  100percentfedup  fake   
3  email kayla mueller was a prisoner and torture...  100percentfedup  fake   
4  email healthcare reform to make america great ...  100percentfedup  fake   

   response  
0         1  
1         1  
2         1  
3         1  
4         1

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [24]:

Y=news_dataset["response"]

#### Splitting data into 70:30 as train and test

In [25]:
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(news_dataset['content'],Y,test_size=0.3)

In [26]:
print(Train_X.shape,Test_X.shape,Train_Y.shape,Test_Y.shape)

(19589,) (8396,) (19589,) (8396,)


#### Applying TFIDF vectorizer

In [27]:
Tfidf_vect = TfidfVectorizer(stop_words='english')
Train_X_Tfidf = Tfidf_vect.fit_transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

#### Applying CountVectorizer

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(stop_words='english')

# Fit and transform the training data 
count_train = count_vectorizer.fit_transform(Train_X) 

# Transform the test set 
count_test = count_vectorizer.transform(Test_X)

In [29]:
print(Train_X_Tfidf.shape,Test_X_Tfidf.shape,count_train.shape,count_test.shape)

(19589, 170121) (8396, 170121) (19589, 170121) (8396, 170121)


#### Applying Naive Bayes Model on TFIDF Vectorizer data

In [30]:
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [31]:
predictions_NB = Naive.predict(Test_X_Tfidf)

In [32]:
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions_NB, Test_Y)*100)

Naive Bayes Accuracy Score ->  70.25964745116721


In [68]:
print(classification_report(Test_Y, predictions_NB))

              precision    recall  f1-score   support

           0       0.66      1.00      0.79      4749
           1       1.00      0.32      0.48      3647

   micro avg       0.70      0.70      0.70      8396
   macro avg       0.83      0.66      0.64      8396
weighted avg       0.80      0.70      0.66      8396



In [69]:
confusion_matrix(Test_Y, predictions_NB)

array([[4748,    1],
       [2496, 1151]], dtype=int64)

#### Naive Bayes model on count vecotizer data

In [33]:
Naive = naive_bayes.MultinomialNB()
Naive.fit(count_train,Train_Y)
predictions1_NB = Naive.predict(count_test)
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions1_NB, Test_Y)*100)

Naive Bayes Accuracy Score ->  85.81467365412101


In [71]:
print(classification_report(Test_Y, predictions1_NB))

              precision    recall  f1-score   support

           0       0.82      0.96      0.88      4749
           1       0.93      0.73      0.82      3647

   micro avg       0.86      0.86      0.86      8396
   macro avg       0.88      0.84      0.85      8396
weighted avg       0.87      0.86      0.85      8396



In [72]:
confusion_matrix(Test_Y, predictions1_NB)

array([[4560,  189],
       [1002, 2645]], dtype=int64)

#### SVM on count vecotizer data

In [34]:
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(count_train,Train_Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
predictions_SVM = SVM.predict(count_test)

print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, Test_Y)*100)

SVM Accuracy Score ->  91.19818961410195


In [50]:
print(classification_report(Test_Y, predictions_SVM))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      4749
           1       0.89      0.91      0.90      3647

   micro avg       0.91      0.91      0.91      8396
   macro avg       0.91      0.91      0.91      8396
weighted avg       0.91      0.91      0.91      8396



In [58]:
confusion_matrix(Test_Y, predictions_SVM)

array([[4333,  416],
       [ 323, 3324]], dtype=int64)

#### SVM on TFIDF vecotizer data

In [36]:
SVM1 = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM1.fit(Train_X_Tfidf,Train_Y)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
predictions_SVM1= SVM1.predict(Test_X_Tfidf)

print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM1, Test_Y)*100)

SVM Accuracy Score ->  93.8423058599333


In [57]:
print(classification_report(Test_Y, predictions_SVM1))

              precision    recall  f1-score   support

           0       0.94      0.95      0.95      4749
           1       0.94      0.92      0.93      3647

   micro avg       0.94      0.94      0.94      8396
   macro avg       0.94      0.94      0.94      8396
weighted avg       0.94      0.94      0.94      8396



In [65]:
confusion_matrix(Test_Y, predictions_SVM1)

array([[4528,  221],
       [ 296, 3351]], dtype=int64)

#### Random Forest model on count vecotizer data

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
rf.fit(count_train,Train_Y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [39]:
predictions_rf = rf.predict(count_test)

print("Random Forest Accuracy Score -> ",accuracy_score(predictions_rf, Test_Y)*100)

Random Forest Accuracy Score ->  56.63411148165793


In [56]:
print(classification_report(Test_Y, predictions_rf))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      4749
           1       1.00      0.00      0.00      3647

   micro avg       0.57      0.57      0.57      8396
   macro avg       0.78      0.50      0.36      8396
weighted avg       0.75      0.57      0.41      8396



In [64]:
confusion_matrix(Test_Y, predictions_rf)

array([[4749,    0],
       [3641,    6]], dtype=int64)

#### Random forest model on TFIDF vecotizer data

In [44]:
rf1= RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
rf1.fit(Train_X_Tfidf,Train_Y)
predictions_rf1 = rf1.predict(Test_X_Tfidf)

print("Random Forest Accuracy Score -> ",accuracy_score(predictions_rf1, Test_Y)*100)

Random Forest Accuracy Score ->  56.56264888041924


In [55]:
print(classification_report(Test_Y, predictions_rf1))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      4749
           1       0.00      0.00      0.00      3647

   micro avg       0.57      0.57      0.57      8396
   macro avg       0.28      0.50      0.36      8396
weighted avg       0.32      0.57      0.41      8396



In [63]:
confusion_matrix(Test_Y, predictions_rf1)

array([[4749,    0],
       [3647,    0]], dtype=int64)

#### Decision tree model on count vecotizer data

In [42]:
import sklearn.tree as tree
dec_tree=tree.DecisionTreeClassifier(max_depth=3,random_state=0)
dec_tree.fit(count_train,Train_Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [43]:
predictions_tree = dec_tree.predict(count_test)

print("Decision tree Accuracy Score -> ",accuracy_score(predictions_tree, Test_Y)*100)

Decision tree Accuracy Score ->  72.6298237255836


In [54]:
print(classification_report(Test_Y, predictions_tree))

              precision    recall  f1-score   support

           0       0.87      0.61      0.72      4749
           1       0.63      0.88      0.74      3647

   micro avg       0.73      0.73      0.73      8396
   macro avg       0.75      0.74      0.73      8396
weighted avg       0.77      0.73      0.72      8396



In [62]:
confusion_matrix(Test_Y, predictions_tree)

array([[2887, 1862],
       [ 436, 3211]], dtype=int64)

#### Decision tree model on TFIDF vecotizer data

In [45]:
dec_tree1=tree.DecisionTreeClassifier(max_depth=3,random_state=0)
dec_tree1.fit(Train_X_Tfidf,Train_Y)
predictions_tree1 = dec_tree1.predict(Test_X_Tfidf)

print("Decision tree Accuracy Score -> ",accuracy_score(predictions_tree1, Test_Y)*100)

Decision tree Accuracy Score ->  71.35540733682706


In [53]:
print(classification_report(Test_Y, predictions_tree1))

              precision    recall  f1-score   support

           0       0.72      0.81      0.76      4749
           1       0.70      0.59      0.64      3647

   micro avg       0.71      0.71      0.71      8396
   macro avg       0.71      0.70      0.70      8396
weighted avg       0.71      0.71      0.71      8396



In [61]:
confusion_matrix(Test_Y, predictions_tree1)

array([[3836,  913],
       [1492, 2155]], dtype=int64)

#### Logistic Regression model on Count vecotizer data

In [46]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression(random_state=0)
log.fit(count_train,Train_Y)
predictions_log= log.predict(count_test)

print("Logistic Regression Accuracy Score -> ",accuracy_score(predictions_log, Test_Y)*100)

Logistic Regression Accuracy Score ->  92.82991900905193


In [52]:
print(classification_report(Test_Y, predictions_log))

              precision    recall  f1-score   support

           0       0.94      0.93      0.94      4749
           1       0.91      0.93      0.92      3647

   micro avg       0.93      0.93      0.93      8396
   macro avg       0.93      0.93      0.93      8396
weighted avg       0.93      0.93      0.93      8396



In [60]:
confusion_matrix(Test_Y, predictions_log)

array([[4412,  337],
       [ 265, 3382]], dtype=int64)

#### Logistic Regression model on TFIDF vecotizer data

In [47]:
log1=LogisticRegression(random_state=0)
log1.fit(Train_X_Tfidf,Train_Y)
predictions_log1= log1.predict(Test_X_Tfidf)

print("Logistic Regression Accuracy Score -> ",accuracy_score(predictions_log1, Test_Y)*100)

Logistic Regression Accuracy Score ->  92.06765126250596


In [51]:
print(classification_report(Test_Y, predictions_log1))

              precision    recall  f1-score   support

           0       0.92      0.95      0.93      4749
           1       0.93      0.89      0.91      3647

   micro avg       0.92      0.92      0.92      8396
   macro avg       0.92      0.92      0.92      8396
weighted avg       0.92      0.92      0.92      8396



In [59]:
confusion_matrix(Test_Y, predictions_log1)

array([[4492,  257],
       [ 409, 3238]], dtype=int64)